### ISSUE TITLE
What ino do I need to upload to the uarm arduino to use this package

### ISSUE THREAD

**Issue by lorenz-halt** [uArm-Developer/UArmForROS#1]
Hi,
I would really like to contribute to this package but I am lacking the arduino knowledge!

**Please help me which ino program to upload (I am a starter for that matter).**

As soon as I have one running example (e.g. rostopic echo ...) I will be happy.

**Comment by myyerrol** [comment]
I think **StandardFirmataEEPROM.ino** in the **examples** folder need to upload.

**Comment by lorenz-halt** [comment]
Thanks, I found another solution: Use the firmwarehelper from pyuarm. Here is my commit for this matter: 68b091657e6ad460011f6aa92ef67697d21b5a61
